clc;clear;close all;
addpath(genpath('methods'));
addpath data
addpath display


k=1;
names={'batch22+23','batch33+43'};

load(names{1,k})   %initial matches generated by SIFT, image pair, and ground truth inliers
X=match.X;
Y=match.Y;
I1=match.I1;
I2=match.I2;
CorrectIndex=match.inliers;
scores=match.scores;

%%%our method
t0=cputime;
[Aff,idxF]=lqRFM(X,Y,scores,0.015,5);
t_our=cputime-t0;
plot_matches(I1, I2, X, Y, idxF,CorrectIndex);
title('our result');
%%%% LLT
[nX, nY, normal]=norm2(X,Y);
if ~exist('conf'), conf = []; end
conf = LLT_init(conf);
method = 'affine';

t0=cputime;
switch method
    case 'affine'
        VecLLT=LLTA(nX, nY, conf);
    case 'rigid'
        VecLLT=LLTR(nX, nY, conf);
    case 'nonrigid'
        VecLLT=LLTV(nX, nY, conf);
end
t_LLT=cputime-t0;
conf=[];

%%%VFC
conf.method = 'VFC';
if ~exist('conf', 'var'), conf = []; end
conf = VFC_init(conf);

t0=cputime;
switch conf.method
    case 'VFC'
        VecFld=VFC(nX, nY-nX, conf);
    case 'FastVFC'
        VecFld=FastVFC(nX, nY-nX, conf);
    case 'SparseVFC'
        VecFld=SparseVFC(nX, nY-nX, conf);
end
t_VFC=cputime-t0;
conf=[];

%%%CSM
nX = [nX, ones(size(nX,1), 1)];
nY = [nY, ones(size(nY,1), 1)];
if ~exist('conf'), conf = []; end
conf = EMTPS_init(conf);

t0=cputime;
Transform=EMTPS(nX, nY, conf.gamma, conf.lambda, conf.theta, conf.a, conf.MaxIter, conf.ecr, conf.minP);
t_CSM=cputime-t0;

%%%RANSAC
t0=cputime;
[Hransac, inliers] = ransacfithomography(X', Y', 0.005);
t_RANSAC=cputime-t0;


%%%evaluate
[precise_ours, recall_ours, inlierRate] = evaluate(CorrectIndex, idxF, size(X,1));
[precise_LLT, recall_LLT, inlierRate] = evaluate(CorrectIndex, VecLLT.VFCIndex, size(X,1));
[precise_VFC, recall_VFC, inlierRate] = evaluate(CorrectIndex, VecFld.VFCIndex, size(X,1));
[precise_CSM, recall_CSM, inlierRate] = evaluate(CorrectIndex, Transform.Index, size(X,1));
[precise_RANSAC, recall_RANSAC, inlierRate] = evaluate(CorrectIndex, inliers, size(X,1));

%%%plot results
plot_matches(I1, I2, X, Y, idxF,CorrectIndex);
title('our result');

plot_matches(I1, I2, X, Y, VecLLT.VFCIndex,CorrectIndex);
title('LLT result');

plot_matches(I1, I2, X, Y, VecFld.VFCIndex,CorrectIndex);
title('VFC result');

plot_matches(I1, I2, X, Y, Transform.Index,CorrectIndex);
title('CSM result');

plot_matches(I1, I2, X, Y, inliers,CorrectIndex);
title('RANSAC result');







